// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYtCYyLxJJ7m7S1Hb7MaajsZEUzNmJnhg',
    appId: '1:404222593905:web:f2d018db653298f0a704d0',
    messagingSenderId: '404222593905',
    projectId: 'mottaina-eat-2',
    authDomain: 'mottaina-eat-2.firebaseapp.com',
    storageBucket: 'mottaina-eat-2.appspot.com',
    measurementId: 'G-7BVSNSNZF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtUWigM1trv78frOZkBJ7hY7SUMExAIBQ',
    appId: '1:404222593905:android:e85a3df60fcbf9e5a704d0',
    messagingSenderId: '404222593905',
    projectId: 'mottaina-eat-2',
    storageBucket: 'mottaina-eat-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtee1zRHGPwtktfaLFJwigXkZcnflSP5A',
    appId: '1:404222593905:ios:03aa640c7abdad71a704d0',
    messagingSenderId: '404222593905',
    projectId: 'mottaina-eat-2',
    storageBucket: 'mottaina-eat-2.appspot.com',
    iosBundleId: 'com.potipoti.colorMuscle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtee1zRHGPwtktfaLFJwigXkZcnflSP5A',
    appId: '1:404222593905:ios:a4e099906f5a2114a704d0',
    messagingSenderId: '404222593905',
    projectId: 'mottaina-eat-2',
    storageBucket: 'mottaina-eat-2.appspot.com',
    iosBundleId: 'com.potipoti.colorMuscle.RunnerTests',
  );
}
